---
- hosts: localhost
  name: satellite_register
  become: yes
  gather_facts: false
  vars:
    var_activationkey: ''
    var_org_id: ''
    var_pool_ids: ''

  tasks:
    - name:  aws-satellite-subscribe
      community.general.redhat_subscription:
        state: present
        activationkey: "{{ var_activationkey }}"
        org_id: "{{ var_org_id }}"
        pool_ids: "{{ var_pool_ids }}"
      register: sat_out

    - name: log sat_out
      debug:
        var: sat_out
